import { Router } from 'express';

export const accountRouter = Router();

// ─── Mock account pool ────────────────────────────────────────────────────────
// 6 accounts covering every common CookieYes support scenario.
// Each account includes: core billing, website details, email activity,
// scan overview, 2FA status, and deletion info.

const MOCK_ACCOUNTS = [

  // ── 1. TechCorp — Professional Annual, healthy, refund-eligible charge ──────
  {
    id: 'acc_pro_001',
    billing_email: 'billing@techcorp.io',
    plan: 'Professional',
    plan_status: 'active',
    billing_cycle: 'annual',
    next_billing_date: '2026-08-15',
    domain: 'techcorp.io',
    banner_active: true,
    banner_version: '3.8.2',
    gcm_enabled: true,
    scanner_last_run: '2026-04-01T10:30:00Z',
    cookies_detected: 42,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2024-03-12T08:00:00Z',
    product: 'cookieyes',
    organization_name: 'TechCorp Solutions',
    pageviews: {
      views: 68420,
      limit: 100000,
      billing_cycle: { start: '2026-04-01', end: '2026-04-30' },
    },
    scan_history: [
      { scan_date: '2026-04-01', scan_status: 'completed', urls_scanned: 24, categories: 8, cookies: 42, scripts: 18, failed_reason: null, scanned_urls: ['https://techcorp.io', 'https://techcorp.io/about', 'https://techcorp.io/pricing', 'https://techcorp.io/blog', 'https://techcorp.io/contact', 'https://techcorp.io/features', 'https://techcorp.io/docs', 'https://techcorp.io/login', 'https://techcorp.io/signup', 'https://techcorp.io/privacy', 'https://techcorp.io/terms', 'https://blog.techcorp.io', 'https://blog.techcorp.io/gdpr-guide', 'https://blog.techcorp.io/cookie-compliance', 'https://app.techcorp.io', 'https://app.techcorp.io/dashboard'] },
      { scan_date: '2026-03-01', scan_status: 'completed', urls_scanned: 22, categories: 7, cookies: 38, scripts: 16, failed_reason: null, scanned_urls: ['https://techcorp.io', 'https://techcorp.io/about', 'https://techcorp.io/pricing', 'https://techcorp.io/blog', 'https://techcorp.io/contact', 'https://techcorp.io/features', 'https://techcorp.io/docs', 'https://techcorp.io/login', 'https://techcorp.io/signup', 'https://techcorp.io/privacy', 'https://techcorp.io/terms', 'https://blog.techcorp.io'] },
      { scan_date: '2026-02-01', scan_status: 'failed',    urls_scanned: 0,  categories: 0, cookies: 0,  scripts: 0,  failed_reason: 'Connection timeout' },
    ],
    cookie_list: [
      { name: 'cookieyes-consent',   category: 'Necessary',     domain: 'techcorp.io',      duration: '1 year',    type: 'first_party', description: 'Stores the user\'s cookie consent preferences.' },
      { name: 'PHPSESSID',           category: 'Necessary',     domain: 'techcorp.io',      duration: 'Session',   type: 'first_party', description: 'Preserves user session state across requests.' },
      { name: 'csrf_token',          category: 'Necessary',     domain: 'techcorp.io',      duration: 'Session',   type: 'first_party', description: 'Protects against cross-site request forgery.' },
      { name: '__stripe_mid',        category: 'Necessary',     domain: '.stripe.com',      duration: '1 year',    type: 'third_party', description: 'Used by Stripe for fraud prevention.' },
      { name: '__stripe_sid',        category: 'Necessary',     domain: '.stripe.com',      duration: '30 minutes',type: 'third_party', description: 'Used by Stripe for session management during checkout.' },
      { name: 'auth_token',          category: 'Necessary',     domain: 'techcorp.io',      duration: '7 days',    type: 'first_party', description: 'Keeps the user authenticated after login.' },
      { name: '_wp_session',         category: 'Necessary',     domain: 'techcorp.io',      duration: 'Session',   type: 'first_party', description: 'WordPress session identifier.' },
      { name: 'wordpress_logged_in', category: 'Necessary',     domain: 'techcorp.io',      duration: '14 days',   type: 'first_party', description: 'Tracks WordPress login state.' },
      { name: '_ga',                 category: 'Analytics',     domain: '.techcorp.io',     duration: '2 years',   type: 'first_party', description: 'Google Analytics — distinguishes unique users.' },
      { name: '_ga_XXXXXXX',         category: 'Analytics',     domain: '.techcorp.io',     duration: '2 years',   type: 'first_party', description: 'Google Analytics 4 session persistence.' },
      { name: '_gid',                category: 'Analytics',     domain: '.techcorp.io',     duration: '24 hours',  type: 'first_party', description: 'Google Analytics — distinguishes users within a session.' },
      { name: '_gat',                category: 'Analytics',     domain: '.techcorp.io',     duration: '1 minute',  type: 'first_party', description: 'Google Analytics — throttles request rate.' },
      { name: '_hjSessionUser',      category: 'Analytics',     domain: '.techcorp.io',     duration: '1 year',    type: 'first_party', description: 'Hotjar — identifies a unique user across sessions.' },
      { name: '_hjSession',          category: 'Analytics',     domain: '.techcorp.io',     duration: 'Session',   type: 'first_party', description: 'Hotjar — contains session data including page view count.' },
      { name: 'ajs_user_id',         category: 'Analytics',     domain: 'techcorp.io',      duration: '1 year',    type: 'first_party', description: 'Segment — stores the user ID for analytics tracking.' },
      { name: 'ajs_anonymous_id',    category: 'Analytics',     domain: 'techcorp.io',      duration: '1 year',    type: 'first_party', description: 'Segment — assigns an anonymous ID to visitors.' },
      { name: 'collect',             category: 'Analytics',     domain: 'google-analytics.com', duration: 'Session', type: 'third_party', description: 'Google Analytics — sends data to Google\'s servers.' },
      { name: 'NID',                 category: 'Analytics',     domain: '.google.com',      duration: '6 months',  type: 'third_party', description: 'Google — registers user preferences and personalises ads.' },
      { name: 'IDE',                 category: 'Marketing',     domain: '.doubleclick.net', duration: '1 year',    type: 'third_party', description: 'Google DoubleClick — tracks conversions and retargeting.' },
      { name: '_fbp',                category: 'Marketing',     domain: '.techcorp.io',     duration: '3 months',  type: 'first_party', description: 'Meta Pixel — identifies browser for ad delivery and measurement.' },
      { name: 'fr',                  category: 'Marketing',     domain: '.facebook.com',    duration: '3 months',  type: 'third_party', description: 'Meta — delivers targeted advertisements on Facebook.' },
      { name: 'VISITOR_INFO1_LIVE',  category: 'Marketing',     domain: '.youtube.com',     duration: '6 months',  type: 'third_party', description: 'YouTube — estimates user bandwidth and stores preferences.' },
      { name: 'YSC',                 category: 'Marketing',     domain: '.youtube.com',     duration: 'Session',   type: 'third_party', description: 'YouTube — tracks video views embedded in the page.' },
      { name: '__hstc',              category: 'Marketing',     domain: '.techcorp.io',     duration: '6 months',  type: 'first_party', description: 'HubSpot — tracks visitor browsing for analytics.' },
      { name: 'hubspotutk',          category: 'Marketing',     domain: '.techcorp.io',     duration: '6 months',  type: 'first_party', description: 'HubSpot — deduplicates contacts from form submissions.' },
      { name: 'li_gc',               category: 'Marketing',     domain: '.linkedin.com',    duration: '6 months',  type: 'third_party', description: 'LinkedIn — stores consent for non-essential cookies.' },
      { name: 'AnalyticsSyncHistory',category: 'Marketing',     domain: '.linkedin.com',    duration: '30 days',   type: 'third_party', description: 'LinkedIn — syncs analytics across LinkedIn properties.' },
      { name: 'intercom-session',    category: 'Functional',    domain: 'techcorp.io',      duration: '7 days',    type: 'first_party', description: 'Intercom — maintains the user\'s Intercom session.' },
      { name: 'intercom-id',         category: 'Functional',    domain: 'techcorp.io',      duration: '9 months',  type: 'first_party', description: 'Intercom — identifies unique visitors for the chat widget.' },
      { name: 'crisp-client',        category: 'Functional',    domain: '.crisp.chat',      duration: '6 months',  type: 'third_party', description: 'Crisp — identifies the chat session.' },
      { name: 'language',            category: 'Functional',    domain: 'techcorp.io',      duration: '1 year',    type: 'first_party', description: 'Stores the user\'s preferred language.' },
      { name: 'timezone',            category: 'Functional',    domain: 'techcorp.io',      duration: '1 year',    type: 'first_party', description: 'Stores the user\'s detected timezone for localisation.' },
      { name: '_uetsid',             category: 'Functional',    domain: '.bing.com',        duration: '1 day',     type: 'third_party', description: 'Microsoft Bing — tracks sessions for analytics.' },
      { name: 'wp-settings-1',       category: 'Preferences',   domain: 'techcorp.io',      duration: '1 year',    type: 'first_party', description: 'WordPress — stores UI preferences for logged-in users.' },
      { name: 'dismissed_notices',   category: 'Preferences',   domain: 'techcorp.io',      duration: '1 year',    type: 'first_party', description: 'Tracks which admin notices the user has dismissed.' },
      { name: 'GTM-PREVIEW',         category: 'Uncategorized', domain: 'techcorp.io',      duration: 'Session',   type: 'first_party', description: 'Google Tag Manager — used during GTM preview mode.' },
      { name: 'x-ms-routing-name',   category: 'Uncategorized', domain: 'techcorp.io',      duration: 'Session',   type: 'first_party', description: 'Azure routing cookie for traffic management.' },
      { name: '_cky_optout',         category: 'Uncategorized', domain: 'techcorp.io',      duration: '1 year',    type: 'first_party', description: 'CookieYes — records user opt-out preference.' },
    ],
    website: {
      cms: 'WordPress',
      script_installed: true,
      script_version: '3.8.2',
      last_consent_logged: '2026-04-05T18:42:00Z',
      auto_block: true,
      geo_targeting: true,
      subdomains: ['blog.techcorp.io', 'app.techcorp.io'],
      consent_rate_percent: 74,
    },
    email_activity: [
      { type: 'invoice',        subject: 'Your CookieYes invoice for April 2026',          sent_at: '2026-04-01T08:00:00Z', delivered: true,  opened: true  },
      { type: 'scan_complete',  subject: 'Scan complete — 42 cookies found on techcorp.io', sent_at: '2026-04-01T10:35:00Z', delivered: true,  opened: true  },
      { type: 'upgrade',        subject: 'You upgraded to Professional Annual',              sent_at: '2026-08-15T09:00:00Z', delivered: true,  opened: true  },
      { type: 'welcome',        subject: 'Welcome to CookieYes!',                           sent_at: '2024-03-12T08:05:00Z', delivered: true,  opened: true  },
    ],
    scan_overview: {
      total_scans: 14,
      last_scan_status: 'completed',
      cookies_by_category: {
        Necessary: 8, Analytics: 12, Marketing: 14, Functional: 5, Uncategorized: 3,
      },
      avg_cookies_per_scan: 40,
      domains_scanned: ['techcorp.io', 'blog.techcorp.io'],
      next_scheduled_scan: '2026-05-01T10:00:00Z',
    },
    two_factor: {
      enabled: true,
      method: 'totp',
      last_enabled_at: '2024-06-01T12:00:00Z',
      last_reset_at: null,
      reset_requested: false,
      reset_requested_at: null,
      backup_codes_remaining: 6,
    },
    deletion_info: {
      deletion_requested: false,
      requested_at: null,
      scheduled_deletion_at: null,
      reason: null,
      data_export_completed: false,
      gdpr_erasure_requested: false,
    },
  },

  // ── 2. ShopNow — Business Monthly, PAYMENT FAILED (card declined) ───────────
  {
    id: 'acc_biz_002',
    billing_email: 'admin@shopnow.com',
    plan: 'Business',
    plan_status: 'past_due',
    billing_cycle: 'monthly',
    next_billing_date: '2026-05-03',
    domain: 'shopnow.com',
    banner_active: true,
    banner_version: '3.8.1',
    gcm_enabled: false,
    scanner_last_run: '2026-04-03T09:00:00Z',
    cookies_detected: 87,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2023-11-01T12:00:00Z',
    product: 'cookieyes',
    organization_name: 'ShopNow Ltd.',
    pageviews: {
      views: 245000,
      limit: 500000,
      billing_cycle: { start: '2026-04-03', end: '2026-05-02' },
    },
    scan_history: [
      { scan_date: '2026-04-03', scan_status: 'completed', urls_scanned: 56, categories: 11, cookies: 87, scripts: 34, failed_reason: null },
      { scan_date: '2026-03-03', scan_status: 'completed', urls_scanned: 54, categories: 10, cookies: 82, scripts: 31, failed_reason: null },
    ],
    website: {
      cms: 'Shopify',
      script_installed: true,
      script_version: '3.8.1',
      last_consent_logged: '2026-04-05T14:10:00Z',
      auto_block: false,
      geo_targeting: false,
      subdomains: [],
      consent_rate_percent: 61,
    },
    email_activity: [
      { type: 'payment_failed', subject: 'Action required: Payment failed for your CookieYes subscription', sent_at: '2026-04-03T08:00:00Z', delivered: true,  opened: false },
      { type: 'payment_failed', subject: 'Second payment attempt failed — please update your card',          sent_at: '2026-04-05T08:00:00Z', delivered: true,  opened: true  },
      { type: 'payment_failed', subject: 'Final notice: Your CookieYes account is past due',                 sent_at: '2026-04-07T08:00:00Z', delivered: true,  opened: false },
      { type: 'invoice',        subject: 'Invoice #INV-2026-039 — Business Plan April 2026',                 sent_at: '2026-04-03T08:01:00Z', delivered: true,  opened: true  },
      { type: 'scan_complete',  subject: 'Scan complete — 87 cookies found on shopnow.com',                  sent_at: '2026-04-03T09:05:00Z', delivered: true,  opened: true  },
    ],
    scan_overview: {
      total_scans: 29,
      last_scan_status: 'completed',
      cookies_by_category: {
        Necessary: 12, Analytics: 22, Marketing: 35, Functional: 9, Preferences: 5, Uncategorized: 4,
      },
      avg_cookies_per_scan: 81,
      domains_scanned: ['shopnow.com'],
      next_scheduled_scan: '2026-05-03T09:00:00Z',
    },
    two_factor: {
      enabled: false,
      method: null,
      last_enabled_at: null,
      last_reset_at: null,
      reset_requested: false,
      reset_requested_at: null,
      backup_codes_remaining: 0,
    },
    deletion_info: {
      deletion_requested: false,
      requested_at: null,
      scheduled_deletion_at: null,
      reason: null,
      data_export_completed: false,
      gdpr_erasure_requested: false,
    },
  },

  // ── 3. Design Studio — Starter Monthly, outside 30-day refund window ────────
  {
    id: 'acc_starter_003',
    billing_email: 'contact@designstudio.co',
    plan: 'Starter',
    plan_status: 'active',
    billing_cycle: 'monthly',
    next_billing_date: '2026-04-22',
    domain: 'designstudio.co',
    banner_active: false,
    banner_version: '3.7.9',
    gcm_enabled: false,
    scanner_last_run: '2026-03-22T14:15:00Z',
    cookies_detected: 18,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2025-07-15T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'Design Studio Co',
    pageviews: {
      views: 9800,
      limit: 25000,
      billing_cycle: { start: '2026-03-22', end: '2026-04-21' },
    },
    scan_history: [
      { scan_date: '2026-03-22', scan_status: 'completed', urls_scanned: 8, categories: 4, cookies: 18, scripts: 7, failed_reason: null },
    ],
    website: {
      cms: 'WordPress',
      script_installed: true,
      script_version: '3.7.9',
      last_consent_logged: '2026-03-30T09:00:00Z',
      auto_block: false,
      geo_targeting: false,
      subdomains: [],
      consent_rate_percent: 55,
    },
    email_activity: [
      { type: 'banner_alert',   subject: '⚠️ Your consent banner has been inactive for 7+ days',         sent_at: '2026-03-29T08:00:00Z', delivered: true,  opened: false },
      { type: 'invoice',        subject: 'Invoice #INV-2026-022 — Starter Plan March 2026',               sent_at: '2026-03-22T08:00:00Z', delivered: true,  opened: true  },
      { type: 'scan_complete',  subject: 'Scan complete — 18 cookies found on designstudio.co',           sent_at: '2026-03-22T14:20:00Z', delivered: true,  opened: true  },
      { type: 'welcome',        subject: 'Welcome to CookieYes!',                                         sent_at: '2025-07-15T00:05:00Z', delivered: true,  opened: true  },
    ],
    scan_overview: {
      total_scans: 9,
      last_scan_status: 'completed',
      cookies_by_category: {
        Necessary: 5, Analytics: 7, Marketing: 4, Uncategorized: 2,
      },
      avg_cookies_per_scan: 17,
      domains_scanned: ['designstudio.co'],
      next_scheduled_scan: '2026-04-22T14:00:00Z',
    },
    two_factor: {
      enabled: true,
      method: 'email',
      last_enabled_at: '2025-08-01T10:00:00Z',
      last_reset_at: '2025-11-15T14:30:00Z',
      reset_requested: false,
      reset_requested_at: null,
      backup_codes_remaining: 3,
    },
    deletion_info: {
      deletion_requested: false,
      requested_at: null,
      scheduled_deletion_at: null,
      reason: null,
      data_export_completed: false,
      gdpr_erasure_requested: false,
    },
  },

  // ── 4. StartupXYZ — AppSumo Lifetime, non-refundable ────────────────────────
  {
    id: 'acc_appsumo_004',
    billing_email: 'founder@startupxyz.io',
    plan: 'AppSumo',
    plan_status: 'active',
    billing_cycle: 'annual',
    next_billing_date: '2027-01-10',
    domain: 'startupxyz.io',
    banner_active: true,
    banner_version: '3.8.2',
    gcm_enabled: false,
    scanner_last_run: '2026-04-02T07:45:00Z',
    cookies_detected: 29,
    regulation: 'CCPA',
    appsumo_deal: true,
    created_at: '2024-01-10T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'StartupXYZ',
    pageviews: {
      views: 11200,
      limit: 50000,
      billing_cycle: { start: '2026-01-10', end: '2027-01-09' },
    },
    scan_history: [
      { scan_date: '2026-04-02', scan_status: 'completed', urls_scanned: 12, categories: 5, cookies: 29, scripts: 11, failed_reason: null },
      { scan_date: '2026-03-02', scan_status: 'completed', urls_scanned: 11, categories: 5, cookies: 27, scripts: 10, failed_reason: null },
    ],
    website: {
      cms: 'Custom',
      script_installed: true,
      script_version: '3.8.2',
      last_consent_logged: '2026-04-05T11:00:00Z',
      auto_block: false,
      geo_targeting: false,
      subdomains: ['app.startupxyz.io'],
      consent_rate_percent: 68,
    },
    email_activity: [
      { type: 'scan_complete', subject: 'Scan complete — 29 cookies found on startupxyz.io', sent_at: '2026-04-02T07:50:00Z', delivered: true, opened: true  },
      { type: 'welcome',       subject: 'Welcome to CookieYes via AppSumo!',                  sent_at: '2024-01-10T00:10:00Z', delivered: true, opened: true  },
    ],
    scan_overview: {
      total_scans: 15,
      last_scan_status: 'completed',
      cookies_by_category: {
        Necessary: 7, Analytics: 10, Marketing: 8, Uncategorized: 4,
      },
      avg_cookies_per_scan: 27,
      domains_scanned: ['startupxyz.io'],
      next_scheduled_scan: '2026-05-02T07:00:00Z',
    },
    two_factor: {
      enabled: false,
      method: null,
      last_enabled_at: null,
      last_reset_at: null,
      reset_requested: true,
      reset_requested_at: '2026-04-04T09:00:00Z',
      backup_codes_remaining: 0,
    },
    deletion_info: {
      deletion_requested: false,
      requested_at: null,
      scheduled_deletion_at: null,
      reason: null,
      data_export_completed: false,
      gdpr_erasure_requested: false,
    },
  },

  // ── 5. Global Retail — Professional Monthly, past_due, deletion requested ───
  {
    id: 'acc_pastdue_005',
    billing_email: 'accounts@globalretail.net',
    plan: 'Professional',
    plan_status: 'past_due',
    billing_cycle: 'monthly',
    next_billing_date: '2026-04-01',
    domain: 'globalretail.net',
    banner_active: true,
    banner_version: '3.8.0',
    gcm_enabled: true,
    scanner_last_run: '2026-03-28T11:00:00Z',
    cookies_detected: 53,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2023-05-20T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'Global Retail Inc.',
    pageviews: {
      views: 98000,
      limit: 100000,
      billing_cycle: { start: '2026-04-01', end: '2026-04-30' },
    },
    scan_history: [
      { scan_date: '2026-03-28', scan_status: 'completed', urls_scanned: 30, categories: 9, cookies: 53, scripts: 22, failed_reason: null },
      { scan_date: '2026-02-28', scan_status: 'completed', urls_scanned: 28, categories: 9, cookies: 50, scripts: 20, failed_reason: null },
    ],
    website: {
      cms: 'WordPress',
      script_installed: true,
      script_version: '3.8.0',
      last_consent_logged: '2026-04-04T20:00:00Z',
      auto_block: true,
      geo_targeting: true,
      subdomains: ['shop.globalretail.net', 'blog.globalretail.net'],
      consent_rate_percent: 82,
    },
    email_activity: [
      { type: 'payment_failed',  subject: 'Action required: Payment failed — please update billing details', sent_at: '2026-04-01T08:00:00Z', delivered: true,  opened: true  },
      { type: 'payment_failed',  subject: 'Final notice: Account suspension in 3 days',                       sent_at: '2026-04-04T08:00:00Z', delivered: true,  opened: true  },
      { type: 'invoice',         subject: 'Invoice #INV-2026-041 — Professional Plan April 2026',              sent_at: '2026-04-01T08:01:00Z', delivered: true,  opened: true  },
      { type: 'scan_complete',   subject: 'Scan complete — 53 cookies on globalretail.net',                    sent_at: '2026-03-28T11:05:00Z', delivered: true,  opened: false },
      { type: 'banner_alert',    subject: '⚠️ Pageview limit at 98% — consider upgrading',                    sent_at: '2026-04-05T09:00:00Z', delivered: true,  opened: true  },
    ],
    scan_overview: {
      total_scans: 34,
      last_scan_status: 'completed',
      cookies_by_category: {
        Necessary: 10, Analytics: 15, Marketing: 18, Functional: 6, Preferences: 2, Uncategorized: 2,
      },
      avg_cookies_per_scan: 51,
      domains_scanned: ['globalretail.net', 'shop.globalretail.net'],
      next_scheduled_scan: '2026-04-28T11:00:00Z',
    },
    two_factor: {
      enabled: true,
      method: 'totp',
      last_enabled_at: '2023-06-01T10:00:00Z',
      last_reset_at: '2026-01-10T15:00:00Z',
      reset_requested: false,
      reset_requested_at: null,
      backup_codes_remaining: 2,
    },
    deletion_info: {
      deletion_requested: true,
      requested_at: '2026-04-05T14:00:00Z',
      scheduled_deletion_at: '2026-04-19T14:00:00Z',
      reason: 'Switching to a competitor product',
      data_export_completed: true,
      gdpr_erasure_requested: true,
      cancellation_reason: 'Price too high for current usage',
    },
  },

  // ── 6. MyBlog — Free plan, no Stripe customer ────────────────────────────────
  {
    id: 'acc_free_006',
    billing_email: 'hello@myblog.dev',
    plan: 'Free',
    plan_status: 'active',
    billing_cycle: 'monthly',
    next_billing_date: '',
    domain: 'myblog.dev',
    banner_active: true,
    banner_version: '3.8.2',
    gcm_enabled: false,
    scanner_last_run: '2026-04-05T16:20:00Z',
    cookies_detected: 6,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2025-12-01T00:00:00Z',
    product: 'cookieyes',
    pageviews: {
      views: 1200,
      limit: 10000,
      billing_cycle: { start: '2026-04-01', end: '2026-04-30' },
    },
    scan_history: [
      { scan_date: '2026-04-05', scan_status: 'completed', urls_scanned: 3, categories: 2, cookies: 6, scripts: 4, failed_reason: null },
    ],
    website: {
      cms: 'WordPress',
      script_installed: true,
      script_version: '3.8.2',
      last_consent_logged: '2026-04-05T17:00:00Z',
      auto_block: false,
      geo_targeting: false,
      subdomains: [],
      consent_rate_percent: 90,
    },
    email_activity: [
      { type: 'scan_complete', subject: 'Scan complete — 6 cookies found on myblog.dev', sent_at: '2026-04-05T16:25:00Z', delivered: true, opened: true  },
      { type: 'welcome',       subject: 'Welcome to CookieYes!',                          sent_at: '2025-12-01T00:05:00Z', delivered: true, opened: true  },
      { type: 'trial_ending',  subject: 'Your free plan is limited — upgrade to unlock more', sent_at: '2026-01-01T09:00:00Z', delivered: true, opened: false },
    ],
    scan_overview: {
      total_scans: 4,
      last_scan_status: 'completed',
      cookies_by_category: {
        Necessary: 3, Analytics: 2, Uncategorized: 1,
      },
      avg_cookies_per_scan: 6,
      domains_scanned: ['myblog.dev'],
      next_scheduled_scan: '2026-05-05T16:00:00Z',
    },
    two_factor: {
      enabled: false,
      method: null,
      last_enabled_at: null,
      last_reset_at: null,
      reset_requested: false,
      reset_requested_at: null,
      backup_codes_remaining: 0,
    },
    deletion_info: {
      deletion_requested: false,
      requested_at: null,
      scheduled_deletion_at: null,
      reason: null,
      data_export_completed: false,
      gdpr_erasure_requested: false,
    },
  },

  // ── 7. MyShop — Professional Monthly, Shopify, auto-block off ───────────────
  {
    id: 'acc_shop_007',
    billing_email: 'hello@myshop.io',
    plan: 'Professional',
    plan_status: 'active',
    billing_cycle: 'monthly',
    next_billing_date: '2026-05-01',
    domain: 'myshop.io',
    banner_active: true,
    banner_version: '3.8.2',
    gcm_enabled: false,
    scanner_last_run: '2026-04-04T10:00:00Z',
    cookies_detected: 34,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2026-01-05T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'MyShop',
    pageviews: { views: 58000, limit: 100000, billing_cycle: { start: '2026-04-01', end: '2026-04-30' } },
    scan_history: [
      { scan_date: '2026-04-04', scan_status: 'completed', urls_scanned: 18, categories: 7, cookies: 34, scripts: 22, failed_reason: null },
    ],
    website: { cms: 'Shopify', script_installed: true, script_version: '3.8.2', last_consent_logged: '2026-04-05T12:00:00Z', auto_block: false, geo_targeting: true, subdomains: [], consent_rate_percent: 63 },
    email_activity: [
      { type: 'invoice', subject: 'Invoice — Professional Plan April 2026', sent_at: '2026-04-01T08:00:00Z', delivered: true, opened: true },
    ],
    scan_overview: { total_scans: 6, last_scan_status: 'completed', cookies_by_category: { Necessary: 5, Analytics: 12, Marketing: 14, Functional: 3 }, avg_cookies_per_scan: 32, domains_scanned: ['myshop.io'], next_scheduled_scan: '2026-05-04T10:00:00Z' },
    two_factor: { enabled: false, method: null, last_enabled_at: null, last_reset_at: null, reset_requested: false, reset_requested_at: null, backup_codes_remaining: 0 },
    deletion_info: { deletion_requested: false, requested_at: null, scheduled_deletion_at: null, reason: null, data_export_completed: false, gdpr_erasure_requested: false },
  },

  // ── 8. AppStack — Starter Monthly, Next.js/Vercel SaaS ──────────────────────
  {
    id: 'acc_saas_008',
    billing_email: 'dev@appstack.dev',
    plan: 'Starter',
    plan_status: 'active',
    billing_cycle: 'monthly',
    next_billing_date: '2026-04-20',
    domain: 'appstack.dev',
    banner_active: true,
    banner_version: '3.8.2',
    gcm_enabled: false,
    scanner_last_run: '2026-04-03T08:00:00Z',
    cookies_detected: 11,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2026-02-20T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'AppStack',
    pageviews: { views: 7200, limit: 25000, billing_cycle: { start: '2026-03-20', end: '2026-04-19' } },
    scan_history: [
      { scan_date: '2026-04-03', scan_status: 'completed', urls_scanned: 5, categories: 3, cookies: 11, scripts: 9, failed_reason: null },
    ],
    website: { cms: 'Custom', script_installed: true, script_version: '3.8.2', last_consent_logged: '2026-04-05T09:00:00Z', auto_block: false, geo_targeting: false, subdomains: ['app.appstack.dev'], consent_rate_percent: 71 },
    email_activity: [
      { type: 'invoice', subject: 'Invoice — Starter Plan March 2026', sent_at: '2026-03-20T08:00:00Z', delivered: true, opened: true },
    ],
    scan_overview: { total_scans: 3, last_scan_status: 'completed', cookies_by_category: { Necessary: 4, Analytics: 5, Functional: 2 }, avg_cookies_per_scan: 10, domains_scanned: ['appstack.dev'], next_scheduled_scan: '2026-05-03T08:00:00Z' },
    two_factor: { enabled: true, method: 'totp', last_enabled_at: '2026-02-21T10:00:00Z', last_reset_at: null, reset_requested: false, reset_requested_at: null, backup_codes_remaining: 8 },
    deletion_info: { deletion_requested: false, requested_at: null, scheduled_deletion_at: null, reason: null, data_export_completed: false, gdpr_erasure_requested: false },
  },

  // ── 9. BlogPress — Professional Monthly, WordPress/WooCommerce, WP Rocket ───
  {
    id: 'acc_blog_009',
    billing_email: 'support@blogpress.net',
    plan: 'Professional',
    plan_status: 'active',
    billing_cycle: 'monthly',
    next_billing_date: '2026-04-25',
    domain: 'blogpress.net',
    banner_active: false,
    banner_version: '3.8.1',
    gcm_enabled: false,
    scanner_last_run: '2026-04-01T09:00:00Z',
    cookies_detected: 28,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2025-10-25T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'BlogPress',
    pageviews: { views: 41000, limit: 100000, billing_cycle: { start: '2026-03-25', end: '2026-04-24' } },
    scan_history: [
      { scan_date: '2026-04-01', scan_status: 'completed', urls_scanned: 14, categories: 6, cookies: 28, scripts: 17, failed_reason: null },
    ],
    website: { cms: 'WordPress', script_installed: true, script_version: '3.8.1', last_consent_logged: '2026-04-03T15:00:00Z', auto_block: false, geo_targeting: false, subdomains: [], consent_rate_percent: 58 },
    email_activity: [
      { type: 'banner_alert', subject: '⚠️ Your consent banner has been inactive for 3+ days', sent_at: '2026-04-05T08:00:00Z', delivered: true, opened: true },
      { type: 'invoice', subject: 'Invoice — Professional Plan March 2026', sent_at: '2026-03-25T08:00:00Z', delivered: true, opened: true },
    ],
    scan_overview: { total_scans: 12, last_scan_status: 'completed', cookies_by_category: { Necessary: 6, Analytics: 9, Marketing: 8, Functional: 3, Uncategorized: 2 }, avg_cookies_per_scan: 26, domains_scanned: ['blogpress.net'], next_scheduled_scan: '2026-05-01T09:00:00Z' },
    two_factor: { enabled: false, method: null, last_enabled_at: null, last_reset_at: null, reset_requested: false, reset_requested_at: null, backup_codes_remaining: 0 },
    deletion_info: { deletion_requested: false, requested_at: null, scheduled_deletion_at: null, reason: null, data_export_completed: false, gdpr_erasure_requested: false },
  },

  // ── 10. BrandSite — Starter Monthly, WordPress + Cloudflare ─────────────────
  {
    id: 'acc_brand_010',
    billing_email: 'tech@brandsite.co',
    plan: 'Starter',
    plan_status: 'active',
    billing_cycle: 'monthly',
    next_billing_date: '2026-04-18',
    domain: 'brandsite.co',
    banner_active: true,
    banner_version: '3.8.0',
    gcm_enabled: false,
    scanner_last_run: '2026-04-02T11:00:00Z',
    cookies_detected: 22,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2025-06-18T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'BrandSite',
    pageviews: { views: 13500, limit: 25000, billing_cycle: { start: '2026-03-18', end: '2026-04-17' } },
    scan_history: [
      { scan_date: '2026-04-02', scan_status: 'completed', urls_scanned: 9, categories: 5, cookies: 22, scripts: 14, failed_reason: null },
    ],
    website: { cms: 'WordPress', script_installed: true, script_version: '3.8.0', last_consent_logged: '2026-04-05T14:00:00Z', auto_block: false, geo_targeting: true, subdomains: [], consent_rate_percent: 69 },
    email_activity: [
      { type: 'invoice', subject: 'Invoice — Starter Plan March 2026', sent_at: '2026-03-18T08:00:00Z', delivered: true, opened: false },
    ],
    scan_overview: { total_scans: 19, last_scan_status: 'completed', cookies_by_category: { Necessary: 4, Analytics: 8, Marketing: 7, Functional: 3 }, avg_cookies_per_scan: 21, domains_scanned: ['brandsite.co'], next_scheduled_scan: '2026-05-02T11:00:00Z' },
    two_factor: { enabled: true, method: 'email', last_enabled_at: '2025-07-01T09:00:00Z', last_reset_at: null, reset_requested: false, reset_requested_at: null, backup_codes_remaining: 4 },
    deletion_info: { deletion_requested: false, requested_at: null, scheduled_deletion_at: null, reason: null, data_export_completed: false, gdpr_erasure_requested: false },
  },

  // ── 11. TechVenture — Professional Monthly, React app, CMP conflict ──────────
  {
    id: 'acc_venture_011',
    billing_email: 'dev@techventure.io',
    plan: 'Professional',
    plan_status: 'active',
    billing_cycle: 'monthly',
    next_billing_date: '2026-04-22',
    domain: 'techventure.io',
    banner_active: true,
    banner_version: '3.8.2',
    gcm_enabled: false,
    scanner_last_run: '2026-04-05T07:00:00Z',
    cookies_detected: 19,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2026-03-17T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'TechVenture',
    pageviews: { views: 22000, limit: 100000, billing_cycle: { start: '2026-03-22', end: '2026-04-21' } },
    scan_history: [
      { scan_date: '2026-04-05', scan_status: 'completed', urls_scanned: 7, categories: 4, cookies: 19, scripts: 12, failed_reason: null },
    ],
    website: { cms: 'Custom', script_installed: true, script_version: '3.8.2', last_consent_logged: '2026-04-05T08:00:00Z', auto_block: false, geo_targeting: true, subdomains: ['app.techventure.io'], consent_rate_percent: 55 },
    email_activity: [
      { type: 'invoice', subject: 'Invoice — Professional Plan March 2026', sent_at: '2026-03-22T08:00:00Z', delivered: true, opened: true },
      { type: 'welcome', subject: 'Welcome to CookieYes!', sent_at: '2026-03-17T00:05:00Z', delivered: true, opened: true },
    ],
    scan_overview: { total_scans: 4, last_scan_status: 'completed', cookies_by_category: { Necessary: 5, Analytics: 8, Marketing: 4, Uncategorized: 2 }, avg_cookies_per_scan: 18, domains_scanned: ['techventure.io'], next_scheduled_scan: '2026-05-05T07:00:00Z' },
    two_factor: { enabled: false, method: null, last_enabled_at: null, last_reset_at: null, reset_requested: false, reset_requested_at: null, backup_codes_remaining: 0 },
    deletion_info: { deletion_requested: false, requested_at: null, scheduled_deletion_at: null, reason: null, data_export_completed: false, gdpr_erasure_requested: false },
  },

  // ── 13. ConsentDemo — Professional Monthly, GCM enabled, ambiguous consent query ─
  {
    id: 'acc_consent_013',
    billing_email: 'admin@consentdemo.io',
    plan: 'Professional',
    plan_status: 'active',
    billing_cycle: 'monthly',
    next_billing_date: '2026-05-05',
    domain: 'consentdemo.io',
    banner_active: true,
    banner_version: '3.8.2',
    gcm_enabled: true,
    scanner_last_run: '2026-04-03T11:00:00Z',
    cookies_detected: 19,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2025-11-10T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'ConsentDemo',
    pageviews: { views: 24000, limit: 100000, billing_cycle: { start: '2026-04-05', end: '2026-05-04' } },
    scan_history: [
      { scan_date: '2026-04-03', scan_status: 'failed', urls_scanned: 0, categories: 0, cookies: 0, scripts: 0, failed_reason: '75_percentage_failed', scanned_urls: [] },
      { scan_date: '2026-04-03', scan_status: 'failed', urls_scanned: 0, categories: 0, cookies: 0, scripts: 0, failed_reason: 'home_page_failed',      scanned_urls: [] },
      { scan_date: '2026-03-25', scan_status: 'failed', urls_scanned: 0, categories: 0, cookies: 0, scripts: 0, failed_reason: '75_percentage_failed',  scanned_urls: [] },
    ],
    cookie_list: [
      { name: 'cookieyes-consent',  category: 'Necessary',  domain: 'consentdemo.io',    duration: '1 year',   type: 'first_party', description: 'Stores the user\'s cookie consent state.' },
      { name: 'PHPSESSID',          category: 'Necessary',  domain: 'consentdemo.io',    duration: 'Session',  type: 'first_party', description: 'Maintains the user\'s PHP session.' },
      { name: 'wp-settings-1',      category: 'Necessary',  domain: 'consentdemo.io',    duration: '1 year',   type: 'first_party', description: 'WordPress UI preferences for logged-in users.' },
      { name: 'wordpress_logged_in',category: 'Necessary',  domain: 'consentdemo.io',    duration: '14 days',  type: 'first_party', description: 'Tracks WordPress login state.' },
      { name: 'csrf_token',         category: 'Necessary',  domain: 'consentdemo.io',    duration: 'Session',  type: 'first_party', description: 'CSRF protection token.' },
      { name: '_ga',                category: 'Analytics',  domain: '.consentdemo.io',   duration: '2 years',  type: 'first_party', description: 'Google Analytics — distinguishes unique users.' },
      { name: '_ga_XXXXXXX',        category: 'Analytics',  domain: '.consentdemo.io',   duration: '2 years',  type: 'first_party', description: 'Google Analytics 4 session persistence.' },
      { name: '_gid',               category: 'Analytics',  domain: '.consentdemo.io',   duration: '24 hours', type: 'first_party', description: 'Google Analytics — distinguishes users within a session.' },
      { name: '_gat_gtag',          category: 'Analytics',  domain: '.consentdemo.io',   duration: '1 minute', type: 'first_party', description: 'Google Analytics — throttles requests.' },
      { name: 'collect',            category: 'Analytics',  domain: 'google-analytics.com', duration: 'Session', type: 'third_party', description: 'Sends analytics data to Google servers.' },
      { name: 'NID',                category: 'Analytics',  domain: '.google.com',       duration: '6 months', type: 'third_party', description: 'Google — registers user preferences.' },
      { name: '_gads',              category: 'Analytics',  domain: '.consentdemo.io',   duration: '13 months',type: 'first_party', description: 'Google Ads — tracks ad clicks and conversions.' },
      { name: 'IDE',                category: 'Marketing',  domain: '.doubleclick.net',  duration: '1 year',   type: 'third_party', description: 'Google — delivers targeted ads via DoubleClick.' },
      { name: '_gcl_au',            category: 'Marketing',  domain: '.consentdemo.io',   duration: '3 months', type: 'first_party', description: 'Google Ads — tracks conversions from ad clicks.' },
      { name: 'VISITOR_INFO1_LIVE', category: 'Marketing',  domain: '.youtube.com',      duration: '6 months', type: 'third_party', description: 'YouTube — estimates bandwidth and stores preferences.' },
      { name: 'YSC',                category: 'Marketing',  domain: '.youtube.com',      duration: 'Session',  type: 'third_party', description: 'YouTube — tracks video views on embedded players.' },
      { name: 'CONSENT',            category: 'Marketing',  domain: '.google.com',       duration: '2 years',  type: 'third_party', description: 'Google — tracks whether the user has accepted Google\'s cookie policy.' },
      { name: 'language',           category: 'Functional', domain: 'consentdemo.io',    duration: '1 year',   type: 'first_party', description: 'Stores the user\'s preferred language.' },
      { name: 'timezone',           category: 'Functional', domain: 'consentdemo.io',    duration: '1 year',   type: 'first_party', description: 'Stores the detected timezone for localisation.' },
    ],
    website: { cms: 'WordPress', script_installed: true, script_version: '3.8.2', last_consent_logged: '2026-04-06T10:00:00Z', auto_block: true, geo_targeting: true, subdomains: [], consent_rate_percent: 72 },
    email_activity: [
      { type: 'invoice', subject: 'Invoice — Professional Plan April 2026', sent_at: '2026-04-05T08:00:00Z', delivered: true, opened: true },
      { type: 'welcome', subject: 'Welcome to CookieYes!', sent_at: '2025-11-10T08:05:00Z', delivered: true, opened: true },
    ],
    scan_overview: { total_scans: 8, last_scan_status: 'completed', cookies_by_category: { Necessary: 5, Analytics: 7, Marketing: 5, Functional: 2 }, avg_cookies_per_scan: 18, domains_scanned: ['consentdemo.io'], next_scheduled_scan: '2026-05-03T11:00:00Z' },
    two_factor: { enabled: false, method: null, last_enabled_at: null, last_reset_at: null, reset_requested: false, reset_requested_at: null, backup_codes_remaining: 0 },
    deletion_info: { deletion_requested: false, requested_at: null, scheduled_deletion_at: null, reason: null, data_export_completed: false, gdpr_erasure_requested: false },
  },

  // ── 12. GCMReady — Professional Monthly, GTM + GCM v2 fully configured ────────
  {
    id: 'acc_gcm_012',
    billing_email: 'privacy@gcmready.io',
    plan: 'Professional',
    plan_status: 'active',
    billing_cycle: 'monthly',
    next_billing_date: '2026-05-10',
    domain: 'gcmready.io',
    banner_active: true,
    banner_version: '3.8.2',
    gcm_enabled: true,
    scanner_last_run: '2026-04-04T09:00:00Z',
    cookies_detected: 16,
    regulation: 'GDPR',
    appsumo_deal: false,
    created_at: '2026-02-10T00:00:00Z',
    product: 'cookieyes',
    organization_name: 'GCMReady',
    pageviews: { views: 31000, limit: 100000, billing_cycle: { start: '2026-04-10', end: '2026-05-09' } },
    scan_history: [
      { scan_date: '2026-04-04', scan_status: 'completed', urls_scanned: 10, categories: 4, cookies: 16, scripts: 11, failed_reason: null },
    ],
    website: { cms: 'WordPress', script_installed: true, script_version: '3.8.2', last_consent_logged: '2026-04-05T16:00:00Z', auto_block: true, geo_targeting: true, subdomains: [], consent_rate_percent: 78 },
    email_activity: [
      { type: 'invoice', subject: 'Invoice — Professional Plan April 2026', sent_at: '2026-04-10T08:00:00Z', delivered: true, opened: true },
    ],
    scan_overview: { total_scans: 7, last_scan_status: 'completed', cookies_by_category: { Necessary: 4, Analytics: 6, Marketing: 4, Functional: 2 }, avg_cookies_per_scan: 15, domains_scanned: ['gcmready.io'], next_scheduled_scan: '2026-05-04T09:00:00Z' },
    two_factor: { enabled: true, method: 'totp', last_enabled_at: '2026-02-11T10:00:00Z', last_reset_at: null, reset_requested: false, reset_requested_at: null, backup_codes_remaining: 8 },
    deletion_info: { deletion_requested: false, requested_at: null, scheduled_deletion_at: null, reason: null, data_export_completed: false, gdpr_erasure_requested: false },
  },
];

function findAccount(email?: string, domain?: string, id?: string) {
  if (id) return MOCK_ACCOUNTS.find((a) => a.id === id) ?? null;
  if (email) {
    const match = MOCK_ACCOUNTS.find(
      (a) => a.billing_email === email || email.includes(a.domain.split('.')[0])
    );
    if (match) return match;
  }
  if (domain) {
    const match = MOCK_ACCOUNTS.find((a) => a.domain === domain || domain.includes(a.domain));
    if (match) return match;
  }
  return null;
}

accountRouter.get('/', (req, res) => {
  const { email, domain, id } = req.query;

  if (!email && !domain && !id) {
    res.status(400).json({ error: 'Provide email, domain, or id' });
    return;
  }

  const account = findAccount(
    email ? String(email) : undefined,
    domain ? String(domain) : undefined,
    id ? String(id) : undefined,
  );

  if (!account) {
    res.status(404).json({ error: 'Account not found' });
    return;
  }

  res.json({ ...account, billing_email: account.billing_email || String(email ?? '') });
});
