import { Router } from 'express';
import axios from 'axios';
import Anthropic from '@anthropic-ai/sdk';

export const autoBugFixRouter = Router();

autoBugFixRouter.post('/', async (req, res) => {
  const { bugTitle, bugDescription, buggyCode, componentName } = req.body;
  const { JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY, ANTHROPIC_API_KEY } = process.env;

  const auth = JIRA_EMAIL && JIRA_API_TOKEN
    ? Buffer.from(`${JIRA_EMAIL}:${JIRA_API_TOKEN}`).toString('base64')
    : null;

  // ── Step 1: Create Jira ticket ──────────────────────────────────────────────
  let jiraKey: string;
  let jiraId: string;
  let jiraUrl: string;

  if (!auth || !JIRA_BASE_URL) {
    jiraKey = `CY-${1000 + Math.floor(Math.random() * 9000)}`;
    jiraId = String(Date.now());
    jiraUrl = `https://cookieyes.atlassian.net/browse/${jiraKey}`;
  } else {
    try {
      const { data } = await axios.post(
        `${JIRA_BASE_URL}/rest/api/3/issue`,
        {
          fields: {
            project: { key: JIRA_PROJECT_KEY || 'CY' },
            issuetype: { name: 'Bug' },
            summary: bugTitle,
            description: {
              type: 'doc',
              version: 1,
              content: [
                {
                  type: 'paragraph',
                  content: [{ type: 'text', text: bugDescription }],
                },
                {
                  type: 'paragraph',
                  content: [
                    { type: 'text', text: `Component: `, marks: [{ type: 'strong' }] },
                    { type: 'text', text: componentName },
                  ],
                },
                {
                  type: 'paragraph',
                  content: [
                    { type: 'text', text: 'Reported via: ', marks: [{ type: 'strong' }] },
                    { type: 'text', text: 'AI Hackathon Demo — Auto Bug Fix' },
                  ],
                },
              ],
            },
            labels: ['auto-reported', 'ai-fix', 'demo'],
          },
        },
        { headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/json' } }
      );
      jiraKey = data.key;
      jiraId = data.id;
      jiraUrl = `${JIRA_BASE_URL}/browse/${data.key}`;
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Jira error';
      res.status(500).json({ error: 'Failed to create Jira ticket', detail: msg });
      return;
    }
  }

  // ── Step 2: Claude analyzes and fixes the bug ───────────────────────────────
  let rootCause = '';
  let fixedCode = '';
  let explanation = '';
  let rawFix = '';

  try {
    const client = new Anthropic({ apiKey: ANTHROPIC_API_KEY });
    const message = await client.messages.create({
      model: 'claude-sonnet-4-6',
      max_tokens: 2048,
      messages: [
        {
          role: 'user',
          content: `You are a senior frontend engineer doing a code review. Analyze the following buggy React/TypeScript component and provide a precise fix.

Bug Title: ${bugTitle}
Bug Description: ${bugDescription}
Component: ${componentName}

Buggy Code:
\`\`\`tsx
${buggyCode}
\`\`\`

Respond in EXACTLY this format (keep the section headers):

## ROOT CAUSE
[One paragraph explaining the bug]

## FIXED CODE
\`\`\`tsx
[Complete fixed code — only the lines that changed, with enough surrounding context to apply the patch]
\`\`\`

## EXPLANATION
[Bullet list of each change made and why]`,
        },
      ],
    });

    rawFix = message.content[0].type === 'text' ? message.content[0].text : '';

    // Parse sections
    const rootMatch = rawFix.match(/## ROOT CAUSE\n([\s\S]*?)(?=\n## )/);
    const codeMatch = rawFix.match(/## FIXED CODE\n```tsx\n([\s\S]*?)```/);
    const explainMatch = rawFix.match(/## EXPLANATION\n([\s\S]*?)$/);

    rootCause = rootMatch ? rootMatch[1].trim() : '';
    fixedCode = codeMatch ? codeMatch[1].trim() : '';
    explanation = explainMatch ? explainMatch[1].trim() : '';
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Claude error';
    res.status(500).json({ error: 'AI analysis failed', detail: msg, jiraKey, jiraUrl });
    return;
  }

  // ── Step 3: Post fix as Jira comment ────────────────────────────────────────
  if (auth && JIRA_BASE_URL) {
    try {
      await axios.post(
        `${JIRA_BASE_URL}/rest/api/3/issue/${jiraKey}/comment`,
        {
          body: {
            type: 'doc',
            version: 1,
            content: [
              {
                type: 'paragraph',
                content: [
                  { type: 'text', text: '🤖 Auto-Fix generated by Claude AI', marks: [{ type: 'strong' }] },
                ],
              },
              {
                type: 'paragraph',
                content: [
                  { type: 'text', text: 'Root Cause: ', marks: [{ type: 'strong' }] },
                  { type: 'text', text: rootCause },
                ],
              },
              {
                type: 'paragraph',
                content: [{ type: 'text', text: 'Fix Details:', marks: [{ type: 'strong' }] }],
              },
              {
                type: 'codeBlock',
                attrs: { language: 'javascript' },
                content: [{ type: 'text', text: fixedCode }],
              },
              {
                type: 'paragraph',
                content: [
                  { type: 'text', text: 'Changes Made: ', marks: [{ type: 'strong' }] },
                  { type: 'text', text: explanation },
                ],
              },
            ],
          },
        },
        { headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/json' } }
      );
    } catch {
      // Comment failed — non-fatal, continue
    }
  }

  res.json({
    jiraKey,
    jiraId,
    jiraUrl,
    rootCause,
    fixedCode,
    explanation,
    rawFix,
  });
});
