import { Router } from 'express';
import axios from 'axios';
import Anthropic from '@anthropic-ai/sdk';

export const jiraRouter = Router();

// ── GET /api/jira/ticket/:key — fetch ticket details + fix comment ────────────
jiraRouter.get('/ticket/:key', async (req, res) => {
  const { key } = req.params;
  const { JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN } = process.env;
  const auth = JIRA_EMAIL && JIRA_API_TOKEN
    ? Buffer.from(`${JIRA_EMAIL}:${JIRA_API_TOKEN}`).toString('base64')
    : null;

  if (!auth || !JIRA_BASE_URL) {
    // Demo fallback when credentials unavailable
    res.json({
      key,
      url: `https://cookieyes.atlassian.net/browse/${key}`,
      summary: '[Demo] Cookie consent widget counts going negative — acmestore.io',
      description: 'Both Accept All and Reject All buttons decrement their counters instead of incrementing. Counters go negative after a few clicks. Acceptance rate shows NaN% on initial load due to division by zero.',
      status: 'Open',
      priority: 'High',
      created: new Date().toISOString(),
      labels: ['auto-reported', 'ai-fix', 'demo'],
      fixComment: null,
    });
    return;
  }

  try {
    const [issueRes, commentsRes] = await Promise.all([
      axios.get(`${JIRA_BASE_URL}/rest/api/3/issue/${key}`, {
        headers: { Authorization: `Basic ${auth}` },
      }),
      axios.get(`${JIRA_BASE_URL}/rest/api/3/issue/${key}/comment`, {
        headers: { Authorization: `Basic ${auth}` },
      }),
    ]);

    const fields = issueRes.data.fields ?? {};

    // Extract plain text from ADF description
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const descText = (fields.description?.content ?? [])
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .flatMap((b: any) => b.content ?? [])
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      .map((t: any) => t.text ?? '')
      .join(' ');

    // Find auto-fix comment
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    let fixComment: string | null = null;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    for (const c of (commentsRes.data.comments ?? []) as any[]) {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const text = (c.body?.content ?? [])
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .flatMap((b: any) => b.content ?? [])
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .map((t: any) => t.text ?? '')
        .join('\n');
      if (text.includes('Auto-Fix generated by Claude AI') || text.includes('FIXED CODE')) {
        fixComment = text;
        break;
      }
    }

    res.json({
      key,
      url: `${JIRA_BASE_URL}/browse/${key}`,
      summary: fields.summary ?? '',
      description: descText,
      status: fields.status?.name ?? 'Open',
      priority: fields.priority?.name ?? 'Medium',
      created: fields.created ?? new Date().toISOString(),
      labels: fields.labels ?? [],
      fixComment,
    });
  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : 'Jira error';
    res.status(500).json({ error: 'Failed to fetch Jira ticket', detail: msg });
  }
});

jiraRouter.post('/issue', async (req, res) => {
  const { ticketId, domain, summary, description } = req.body;
  const { JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN, JIRA_PROJECT_KEY } = process.env;

  // Demo mode: no Jira credentials → return a realistic mock ticket
  if (!JIRA_BASE_URL || !JIRA_EMAIL || !JIRA_API_TOKEN) {
    const mockKey = `CY-${1000 + Math.floor(Math.random() * 9000)}`;
    res.json({
      id: String(Date.now()),
      key: mockKey,
      url: `https://cookieyes.atlassian.net/browse/${mockKey}`,
      status: 'created',
      summary: summary || `[Banner not loading] ${domain} — Zendesk #${ticketId}`,
      created: new Date().toISOString(),
    });
    return;
  }

  try {
    const auth = Buffer.from(`${JIRA_EMAIL}:${JIRA_API_TOKEN}`).toString('base64');
    const { data } = await axios.post(
      `${JIRA_BASE_URL}/rest/api/3/issue`,
      {
        fields: {
          project: { key: JIRA_PROJECT_KEY || 'CY' },
          issuetype: { name: 'Bug' },
          summary: summary || `[Banner not loading] ${domain} — Zendesk #${ticketId}`,
          description: {
            type: 'doc',
            version: 1,
            content: [{ type: 'paragraph', content: [{ type: 'text', text: description || '' }] }],
          },
          labels: ['banner', 'customer-reported', 'cx-escalation'],
        },
      },
      { headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/json' } }
    );

    res.json({
      id: data.id,
      key: data.key,
      url: `${JIRA_BASE_URL}/browse/${data.key}`,
      status: 'created',
      summary: summary || `[Banner not loading] ${domain} — Zendesk #${ticketId}`,
      created: new Date().toISOString(),
    });
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : 'Jira error';
    res.status(500).json({ error: 'Jira issue creation failed', detail: message });
  }
});

// ── Known demo buggy code (used when Jira comments don't have a fix yet) ──────
const DEMO_BUGGY_CODE = `function ConsentStatsWidget() {
  const [accepted, setAccepted] = useState(0);
  const [rejected, setRejected] = useState(0);

  // Bug 1: decrements instead of incrementing accepted count
  const handleAccept = () => setAccepted(c => c - 1);

  // Bug 2: decrements instead of incrementing rejected count
  const handleReject = () => setRejected(c => c - 1);

  const total = accepted + rejected;

  // Bug 3: no zero-guard — shows NaN% when total is 0
  const acceptRate = Math.round((accepted / total) * 100);

  return (
    <div>
      <button onClick={handleAccept}>Accept All</button>
      <button onClick={handleReject}>Reject All</button>
      <p>Accepted: {accepted}</p>
      <p>Rejected: {rejected}</p>
      <p>Rate: {acceptRate}%</p>
    </div>
  );
}`;

// ── POST /api/jira/apply-fix ──────────────────────────────────────────────────
// Given a Jira ticket key:
//   1. Fetch the ticket + comments from Jira
//   2. Look for an auto-fix comment posted by this system
//   3. If found → return the fix
//   4. If not → call Claude to generate + post the fix
jiraRouter.post('/apply-fix', async (req, res) => {
  const { jiraKey } = req.body as { jiraKey: string };
  if (!jiraKey?.trim()) {
    res.status(400).json({ error: 'jiraKey is required' });
    return;
  }

  const { JIRA_BASE_URL, JIRA_EMAIL, JIRA_API_TOKEN, ANTHROPIC_API_KEY } = process.env;
  const auth = JIRA_EMAIL && JIRA_API_TOKEN
    ? Buffer.from(`${JIRA_EMAIL}:${JIRA_API_TOKEN}`).toString('base64')
    : null;

  let ticketSummary = '';
  let ticketDescription = '';
  let existingFix: { rootCause: string; fixedCode: string; explanation: string } | null = null;

  // ── Step 1: Fetch ticket + comments from Jira ──────────────────────────────
  if (auth && JIRA_BASE_URL) {
    try {
      const [issueRes, commentsRes] = await Promise.all([
        axios.get(`${JIRA_BASE_URL}/rest/api/3/issue/${jiraKey}`, {
          headers: { Authorization: `Basic ${auth}` },
        }),
        axios.get(`${JIRA_BASE_URL}/rest/api/3/issue/${jiraKey}/comment`, {
          headers: { Authorization: `Basic ${auth}` },
        }),
      ]);

      ticketSummary = issueRes.data.fields?.summary ?? '';
      // Extract plain text from ADF description
      const descContent = issueRes.data.fields?.description?.content ?? [];
      ticketDescription = descContent
        .flatMap((b: { content?: { text?: string }[] }) => b.content ?? [])
        .map((t: { text?: string }) => t.text ?? '')
        .join(' ');

      // Look for an existing auto-fix comment
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const comments: any[] = commentsRes.data.comments ?? [];
      for (const c of comments) {
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const bodyText = (c.body?.content ?? [])
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          .flatMap((b: any) => b.content ?? [])
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          .map((t: any) => t.text ?? '')
          .join('\n');

        if (bodyText.includes('Auto-Fix generated by Claude AI') || bodyText.includes('FIXED CODE')) {
          // Extract code block
          const codeMatch = bodyText.match(/```[\w]*\n([\s\S]*?)```/);
          if (codeMatch) {
            existingFix = {
              rootCause: 'Fix retrieved from Jira ticket comments (previously generated by Claude AI).',
              fixedCode: codeMatch[1].trim(),
              explanation: bodyText.split('Changes Made:')[1]?.trim() ?? '',
            };
            break;
          }
        }
      }
    } catch {
      // Jira fetch failed — fall through to Claude generation
    }
  }

  // ── Step 2: If no existing fix, call Claude ────────────────────────────────
  if (!existingFix) {
    try {
      const client = new Anthropic({ apiKey: ANTHROPIC_API_KEY });
      const message = await client.messages.create({
        model: 'claude-sonnet-4-6',
        max_tokens: 2048,
        messages: [
          {
            role: 'user',
            content: `You are a senior frontend engineer. Analyze this buggy React component and provide a precise fix.

Jira Ticket: ${jiraKey}
Summary: ${ticketSummary || 'Cookie consent widget counts going negative'}
Customer Report: ${ticketDescription || 'Accept All and Reject All buttons decrement counters instead of incrementing. Shows NaN% on initial load.'}

Buggy Code:
\`\`\`tsx
${DEMO_BUGGY_CODE}
\`\`\`

Respond in EXACTLY this format:

## ROOT CAUSE
[One paragraph]

## FIXED CODE
\`\`\`tsx
[Only the changed lines with enough surrounding context]
\`\`\`

## EXPLANATION
[Bullet list of each change and why]`,
          },
        ],
      });

      const raw = message.content[0].type === 'text' ? message.content[0].text : '';
      const rootMatch = raw.match(/## ROOT CAUSE\n([\s\S]*?)(?=\n## )/);
      const codeMatch = raw.match(/## FIXED CODE\n```tsx\n([\s\S]*?)```/);
      const explainMatch = raw.match(/## EXPLANATION\n([\s\S]*?)$/);

      existingFix = {
        rootCause: rootMatch?.[1]?.trim() ?? '',
        fixedCode: codeMatch?.[1]?.trim() ?? '',
        explanation: explainMatch?.[1]?.trim() ?? '',
      };

      // Post the fix as a comment back to Jira
      if (auth && JIRA_BASE_URL) {
        try {
          await axios.post(
            `${JIRA_BASE_URL}/rest/api/3/issue/${jiraKey}/comment`,
            {
              body: {
                type: 'doc',
                version: 1,
                content: [
                  {
                    type: 'paragraph',
                    content: [{ type: 'text', text: '🤖 Auto-Fix generated by Claude AI', marks: [{ type: 'strong' }] }],
                  },
                  {
                    type: 'paragraph',
                    content: [
                      { type: 'text', text: 'Root Cause: ', marks: [{ type: 'strong' }] },
                      { type: 'text', text: existingFix.rootCause },
                    ],
                  },
                  {
                    type: 'codeBlock',
                    attrs: { language: 'javascript' },
                    content: [{ type: 'text', text: existingFix.fixedCode }],
                  },
                  {
                    type: 'paragraph',
                    content: [
                      { type: 'text', text: 'FIXED CODE — applied to demo page widget.' },
                    ],
                  },
                ],
              },
            },
            { headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/json' } }
          );
        } catch {
          // Non-fatal
        }
      }
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Claude error';
      res.status(500).json({ error: 'Failed to generate fix', detail: msg });
      return;
    }
  }

  res.json({
    jiraKey,
    jiraUrl: JIRA_BASE_URL ? `${JIRA_BASE_URL}/browse/${jiraKey}` : `https://cookieyes.atlassian.net/browse/${jiraKey}`,
    ...existingFix,
  });
});
